window.CONFIG = Object.freeze({
  WIDTH: 1280,
  HEIGHT: 720,

  PLAYER_SPEED: 5,
  PLAYER_HEIGHT: 1.8,
  PLAYER_CROUCH_HEIGHT: 1.0,
  INTERACT_RANGE: 2.5,
  MAX_STICKERS: 15,

  DRONE_SPEED: 8,
  DRONE_MAX_ALTITUDE: 25,
  DRONE_EXPLOSION_RADIUS: 3,
  DRONE_BATTERY: 120,

  GUARD_SIGHT_RANGE: 15,
  GUARD_SIGHT_ANGLE: 60,
  GUARD_HEAR_RANGE: 8,
  DISGUISE_SUSPICION_RATE: 0.05,
  MAX_SUSPICION: 100,

  // كل البنية التحتية للدولة المحتلة (10 مواقع)
  LOCATIONS: [
    'weapons_factory',
    'central_bank',
    'power_plant',
    'comm_center',
    'oil_refinery',
    'command_center',
    'military_airport',
    'water_plant',
    'metal_factory',
    'ammo_depot',
  ],

  LOCATION_NAMES: {
    weapons_factory:  'مصنع الأسلحة',
    central_bank:     'البنك المركزي',
    power_plant:      'محطة الكهرباء',
    comm_center:      'مركز الاتصالات',
    oil_refinery:     'مصفاة النفط',
    command_center:   'مركز القيادة العسكري',
    military_airport: 'المطار العسكري',
    water_plant:      'محطة المياه',
    metal_factory:    'مصنع المعادن',
    ammo_depot:       'مستودع الذخيرة',
  },

  LOCATION_DIFFICULTY: {
    weapons_factory:  3,
    central_bank:     2,
    power_plant:      2,
    comm_center:      2,
    oil_refinery:     3,
    command_center:   4,
    military_airport: 3,
    water_plant:      1,
    metal_factory:    1,
    ammo_depot:       4,
  },

  GUARDS_PER_LOCATION: {
    weapons_factory:  6,
    central_bank:     5,
    power_plant:      4,
    comm_center:      4,
    oil_refinery:     5,
    command_center:   8,
    military_airport: 7,
    water_plant:      3,
    metal_factory:    4,
    ammo_depot:       8,
  },

  TARGETS_PER_LOCATION: {
    weapons_factory:  4,
    central_bank:     3,
    power_plant:      4,
    comm_center:      3,
    oil_refinery:     5,
    command_center:   4,
    military_airport: 4,
    water_plant:      3,
    metal_factory:    3,
    ammo_depot:       5,
  },

  // نوع الهدف لكل موقع
  TARGET_TYPES: {
    weapons_factory:  ['missile_storage', 'assembly_line', 'fuel_tank', 'armoury'],
    central_bank:     ['vault_server', 'currency_reserve', 'security_system'],
    power_plant:      ['turbine', 'cooling_system', 'control_room', 'transformer'],
    comm_center:      ['satellite_dish', 'transmitter', 'server_rack'],
    oil_refinery:     ['distillation_col', 'storage_tank', 'pump', 'pipeline', 'gas_valve'],
    command_center:   ['radar_array', 'command_terminal', 'fuel_depot', 'comms_hub'],
    military_airport: ['fuel_tanks', 'control_tower', 'hangar', 'runway_lights'],
    water_plant:      ['main_pump', 'purification', 'reservoir_valve'],
    metal_factory:    ['smelter', 'casting_machine', 'gas_system'],
    ammo_depot:       ['explosive_storage', 'loading_bay', 'cooling_system', 'detonator_rack', 'fuel_line'],
  },

  GRAVITY: -9.8,
  COLLISION_LAYERS: { WORLD: 1, PLAYER: 2, DRONE: 4, GUARD: 8, OBJECT: 16 },

  COLORS: {
    FLOOR:            0x2a2a2a,
    WALL:             0x444444,
    CEILING:          0x1a1a1a,
    ALIEN_SKIN:       0x00ff88,
    GUARD_UNIFORM:    0x1a1a4e,
    STICKER_ACTIVE:   0x00ffff,
    STICKER_TRIGGERED:0xff4400,
    TARGET_NORMAL:    0x886600,
    TARGET_TAGGED:    0x00ff00,
    MACHINE:          0x777777,
    EXPLOSION:        0xff3300,
    DRONE:            0x111111,
    ALERT_LOW:        0xffff00,
    ALERT_HIGH:       0xff0000,
    BANK_GOLD:        0xffd700,
    POWER_BLUE:       0x4488ff,
    OIL_DARK:         0x222200,
    MILITARY_GREEN:   0x2d4a1e,
  },

  MASTER_VOLUME: 0.7,
  SFX_VOLUME: 0.8,
  AMBIENT_VOLUME: 0.4,

  DB_NAME: 'NexoInfiltrator',
  DB_VERSION: 1,
  SAVE_KEY: 'nexo_save',
});
